### ISSUE TITLE
Creating Asset Layout - Missing Custom Field Options

### ISSUE THREAD

**Issue by ZzBombardierzZ** [msoukhomlinov/n8n-nodes-hudu#8]
When creating an asset layout with custom fields, there's no option to add the hint variable to the custom field. More importantly, if you're creating a custom field of type "AssetLink", there's no option to choose the linkable asset layout id. Lastly, reviewing the email below from Hudu support reminded me that there's also "expiration", "min", "max", and others missing.

The API docs don't show hints or asset links, but when I've used https://github.com/lwhitelock/HuduAPI I have been able to add both as so: 
![Image](https://github.com/user-attachments/assets/e9466c53-8a28-4972-b9b9-df9710d42a1d)

Hudu support was the one who told me to use "linkable_id" in the field data for assetlinks.

![Image](https://github.com/user-attachments/assets/18c592e7-01ae-4cd4-9c09-e0bd102f4f5a)

I'm not familiar with the limitations of creating n8n nodes. If you can't exclusively add "min" and "max" for only number types, "linkable_id" for AssetLinks, "expiration" for dates, and "options"/"mutliple_options"/"list_id" for Lists, maybe you could add an "other data" input field on all types to add these sorts of things.

**Comment by msoukhomlinov** [comment]
Fixed in v1.3.3, please give it a try and confirm.

**Comment by ZzBombardierzZ** [comment]
> Fixed in v1.3.3, please give it a try and confirm.

I still don't see an option to give a linkable_id, but I may be missing something:

![Image](https://github.com/user-attachments/assets/f6f2bb4f-b091-439b-bbb9-633d0640832a)

**Comment by msoukhomlinov** [comment]
@ZzBombardierzZ , did you restart n8n after updating the node?

**Comment by ZzBombardierzZ** [comment]
@msoukhomlinov - I did, and did it again just in case, and there's still no option to add a linkable_id when you add an asset link field.

**Comment by msoukhomlinov** [comment]
@ZzBombardierzZ , please update to 1.3.5, working with asset fields has been completely reworked to better align with n8n limitations and Hudu API. Please review the changelog for details.

**Comment by msoukhomlinov** [comment]
@ZzBombardierzZ , to update 20 fields you dont have to have 20 steps, you will need upto 3 (one for standard fields, one for custom and one for link/assetlink fields.

I'll look at the Asset Layout issue when I have a moment, must have misunderstood your request.

**Comment by ZzBombardierzZ** [comment]
I could be mistaken, by when I tested the node yesterday; there wasn’t an
option to add more than 1 field. So if I wanted to update 3 custom fields
on an asset, I would need 3 nodes.

 I’ve reverted the update in the meantime, but can test more on Monday.

**Comment by msoukhomlinov** [comment]
@ZzBombardierzZ , actually you are right, i'll see if I can refactor it into a resource mapper so multiple fields could be done at once.

**Comment by ZzBombardierzZ** [comment]
@msoukhomlinov - still no option to specify which asset layout an assetLink links to when creating a new Asset Layout, nor to add a hint:

![Image](https://github.com/user-attachments/assets/f04666af-4aaf-4719-9341-6279c8f47199)





I'm guessing a lot there's a lot of AI coding involved with making this n8n node. The example API request in the API docs shows only the following fields:

`"fields": [
      {
        "label": "Name-of-the-field-here",
        "field_type": "type-of-field-here E.g. Text, RichText, Number",
        "required": true,
        "show_in_list": true,
        "position": 1
      },
      {
        "label": "Another-field-name-here",
        "field_type": "Another-type-of-field E.g. Text, RichText, Number",
        "required": false,
        "show_in_list": false,
        "position": 2
      }
    ]`

![Image](https://github.com/user-attachments/assets/801188ba-9df8-4692-9414-13ceb9978c62)

However; it actually supports many more fields as you can see in the example response:

`"fields": [
      {
        "id": 0,
        "label": "string",
        "show_in_list": true,
        "field_type": "string",
        "required": true,
        "hint": "string",
        "min": 0,
        "max": 0,
        "linkable_id": 0,
        "expiration": true,
        "options": "string",
        "position": 0,
        "is_destroyed": true
      }`

![Image](https://github.com/user-attachments/assets/48a0f4b9-2da0-4e66-a4eb-00170863e4b3)



If I knew how to set up a dev instance of this node, I would love to try and help, but I don't understand the n8n docs for setting up a dev instance on npm nodes. and I'm not much of a javascript/npm guy.

**Comment by msoukhomlinov** [comment]
The functionality of Asset Layouts is split across two resources: Asset Layouts and Asset Layout Fields. The latter allows you to adjust parameters for Asset Layout Fields once they have been created (such as adding hints, etc.). 

Also note that whatever you see in Swagger for the example of request (not response from the API) is the complete list of fields that is officially supported by the Hudu API. As an example, I've tried to set list_id for a list field, API response confirmed it was done, however, the change was not reflected in the DB (subsequent get confirmed it was unchanged). 

I am seeking clarification from support if these asset layout field parameters are accessible for r/w via API, and if so, what are the options fo the likes of column_width: 
list_id
column_width
options
is_destroyed
